name: Release

on:
  push:
    branches:
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install
      - name: Publish extension to marketplace
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"

          # Delete pushed version tag to conflict tag 'vsce publish' created
          git tag -d "v${RELEASE_VERSION}"
          git push origin ":v${RELEASE_VERSION}"

          npx vsce publish $RELEASE_VERSION -p $AZURE_ACCESS_TOKEN -m "Bump up version ${RELEASE_VERSION}"
        env:
          AZURE_ACCESS_TOKEN: ${{ secrets.AZURE_ACCESS_TOKEN }}
